# Generated by Django 5.0.6 on 2024-06-10 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_item_delete_invetory_survivor_infected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='survivor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='base.survivor'),
        ),
    ]
